version: "3"

services:

  osmosisd:
    image: osmolabs/osmosis:10.0.1
    user: $UID:$GID
    volumes:
      - ./osmosis:/osmosis/.osmosisd
    command:
      - start
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
  
  junod:
    image: ghcr.io/cosmoscontracts/juno:9.0
    user: 0:0
    volumes:
    - ./juno/:/root/.juno/
    command: 
    - ./setup_and_run.sh 
    - juno16g2rahf5846rxzp3fwlswy08fz8ccuwk03k57y
    ports:
      - "36656:26656"
      - "36657:26657"
      - "3317:1317"
    environment:
      - GAS_LIMIT=${GAS_LIMIT:-100000000}
      - STAKE_TOKEN=${STAKE_TOKEN:-ustake}
      - CHAIN_ID=${CHAIN_ID:-localjuno}
      - MONIKER=${MONIKER:-node-0}
  
  
  
