version: "3"

services:

  osmosisd:
    image: osmolabs/osmosis:10.0.1
    user: $UID:$GID
    volumes:
      - ./osmosis/config:/osmosis/.osmosisd/config
      - ./osmosis/data:/osmosis/.osmosisd/data
      - ./osmosis/wasm:/osmosis/.osmosisd/wasm
    command:
      - start
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
  
  gaiad:
    image: osmolabs/gaia:7.0.1
    user: $UID:$GID
    volumes:
      - ./gaia/config:/gaia/.gaiad/config
      - ./gaia/data:/gaia/.gaiad/data
    command:
      - start
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
  
  
